server:
   port: 8099
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/data
    username: root
    password: PASSWORD
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dilect: org.hibernate.dialect.MySQLDialect
  application:
    name: HOTEL-SERVICE
      
      
      
eureka: 
    instance:
      prefer-ip-address: true
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
 